name: Linux

on: [push, pull_request]

jobs:
  tabs:
    name: Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tabs
        run: .github/workflows/style/check_tabs.py
  docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: installing preliminaries
      run: bash .github/workflows/dependencies.sh
    - name: make
      run: make docs
  test-2d:
    name: Build & Test (2D)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: installing preliminaries
      run: bash .github/workflows/dependencies.sh
    - name: configure (2d)
      run: ./configure --dim=2 
    - name: make
      run: make
    - name: unit tests
      run: ./bin/test-2d-g++
    - name: regression tests
      run: scripts/runtests.py --serial --dim=2 --benchmark=github
  test-3d:
    name: Build & Test (3D)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: installing preliminaries
      run: bash .github/workflows/dependencies.sh
    - name: configure
      run: ./configure --dim=3 
    - name: make
      run: make
    - name: unit tests
      run: ./bin/test-3d-g++
    - name: regression tests
      run: scripts/runtests.py --serial --dim=3 --benchmark=github
